projects:
  trademate:
    schemaPath: amplify/backend/api/trademate/build/schema.graphql
    includes:
      - src/graphql/queries.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: ap-southeast-2
        apiId: null
        maxDepth: 2
