projects:
  trademate:
    schemaPath: amplify/backend/api/trademate/build/schema.graphql
    includes:
      - amplify/backend/api/trademate/build/functions/Test.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: amplify/backend/api/trademate/build/functions
        region: ap-southeast-2
        apiId: null
        maxDepth: 2
