import React from 'react';
import './App.css';

// Imports the Amplify library from 'aws-amplify' package. This is used to configure your app to interact with AWS services.
import {Amplify} from 'aws-amplify';

// Imports the Authenticator and withAuthenticator components from '@aws-amplify/ui-react'.
// Authenticator is a React component that provides a ready-to-use sign-in and sign-up UI.
// withAuthenticator is a higher-order component that wraps your app component to enforce authentication.
// Imports the default styles for the Amplify UI components. This line ensures that the authenticator looks nice out of the box.
import '@aws-amplify/ui-react/styles.css';

// Imports the awsExports configuration file generated by the Amplify CLI. This file contains the AWS service configurations (like Cognito, AppSync, etc.) specific to your project.
import awsExports from './aws-exports';
// Imports the Quiz component from Quiz.js for use in this file.
import NavBarHeader2 from './ui-components/NavBarHeader2';
import MarketingFooterBrand from './ui-components/MarketingFooterBrand';
import HeroLayout1 from './ui-components/HeroLayout1';
import Home from './pages/Home';
// Configures the Amplify library with the settings from aws-exports.js, which includes all the AWS service configurations for this project.
Amplify.configure(awsExports);

function App() {
  const overrideProps = {

    NavBarHeader2: {
        width: '100%', // 修改导航栏宽度
        backgroundColor: '#fff', // 修改导航栏背景颜色
    },
    "logo":{
      src: "/logo.png", // 修改logo图片
      alt: "Amazon Connect",
    },
    Button39493466: {
      children: 'Sign Up', // 修改按钮的文本
    },
    Button39493467: {
      children: 'Log In', // 修改按钮的文本
    },

  };

  return (
    <div className="App">
      <NavBarHeader2 overrides={overrideProps} ></NavBarHeader2>
      
      <main>
          <HeroLayout1 width={"100%"}/>
      </main>
        <MarketingFooterBrand />

    </div>
  );
}

export default App;